---

- name: Configure kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: True
    state: present
    reload: True
  with_dict:
    vm.max_map_count: '262144'
  register: kernel_params
  tags:
    - configuration
    - system
    - kernel

- name: Create elasticsearch directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: False 
    owner: "{{ elasticsearch_docker_container_user_uid }}"
    group: "{{ elasticsearch_docker_container_group_uid }}"
  with_items:
    - "{{ elasticsearch_config_dir }}"
    - "{{ elasticsearch_data_dir }}"
    - "{{ elasticsearch_certificate_dir }}"
    - "{{ elasticsearch_snapshot_dir_host }}"
  register: dir_create
  tags:
    - configuration
    - files

- include_tasks: lvm.yml
  when: elasticsearch_lvm_storage_enable
  tags:
    - configuration
    - system
    - storage

- name: Copy SSL certificates
  copy:
    src: "{{ elasticsearch_certificate_local_dir|default('certificates') }}/"
    dest: "{{ elasticsearch_certificate_dir  }}/"
    mode: 0440
    owner: "{{ elasticsearch_docker_container_user_uid }}"
    group: "{{ elasticsearch_docker_container_group_uid }}"
  register: copy_certs
  tags:
    - configuration
    - files
    - certificates

- name: Load secrets
  include_vars:
    file: "{{ lookup('env', 'PWD') }}/{{ elasticsearch_secrets_file|default('vault/secrets.yml')}}"
  tags:
    - configuration

- name: Copy role mapping file
  template:
    src: role_mapping.j2
    dest: "{{ elasticsearch_config_dir  }}/role_mapping.yml"
    owner: "{{ elasticsearch_docker_container_user_uid }}"
    group: "{{ elasticsearch_docker_container_group_uid }}"
  register: es_role_mapping
  tags:
    - configuration
    - files
    - roles

- name: Copy elasticsearch configuration
  template:
    src: elasticsearch.j2
    dest: "{{ elasticsearch_config_dir }}/elasticsearch.yml"
    owner: "{{ elasticsearch_docker_container_user_uid }}"
    group: "{{ elasticsearch_docker_container_group_uid }}"
  register: es_config
  tags:
    - configuration
    - files

- name: Remove elasticsearch keystore
  file:
    path: "{{ elasticsearch_config_dir }}/elasticsearch.keystore"
    state: absent
  when: elasticsearch_force_keystore_create
  tags:
    - configuration
    - files
    - keystore

- name: Create elasticsearch keystore
  command: "docker run --rm -i -v {{ elasticsearch_config_dir }}:/usr/share/elasticsearch/config:rw,Z -v {{ elasticsearch_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z {{ elasticsearch_docker_image }}:{{ elasticsearch_docker_tag   }} elasticsearch-keystore create"
  args:
    creates: "{{ elasticsearch_config_dir }}/elasticsearch.keystore"
  register: keystore_create
  tags:
    - configuration
    - files
    - keystore

- name: Add elasticsearch keystore keys
  command: "docker run --rm -i -v {{ elasticsearch_config_dir }}:/usr/share/elasticsearch/config:rw,Z -v {{ elasticsearch_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z {{ elasticsearch_docker_image }}:{{ elasticsearch_docker_tag   }} elasticsearch-keystore add --stdin {{ item.key }}"
  args:
    stdin: "{{ item.value }}"
  with_dict: "{{ secrets.elasticsearch.keystore }}"
  when: keystore_create.changed
  register: keystore_write
  tags:
    - configuration
    - files
    - keystore

- name: Pre-restart cluster actions
  uri:
    method: "{{ item.value.method }}"
    url_username: elastic
    url_password: "{{ secrets.elasticsearch.bootstrap.password }}"
    url: "{% if elasticsearch_security_http_enabled %}https{% else %}http{% endif %}://{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}/{{ item.value.path }}"
    remote_src: True
    return_content: True
    validate_certs: False
    body_format: json
    body: "{{ item.value.body }}"
  run_once: True
  with_dict: "{{ pre_restart_actions }}"
  when: elasticsearch_pre_restart_actions and ( copy_certs.changed or es_config.changed or keystore_create.changed or kernel_params.changed )
  register: pre_restart_actions
  tags:
    - configuration
    - api

- name: Deploy elasticsearch containers
  docker_container:
    state: started
    restart: "{{ (copy_certs is defined and copy_certs.changed) or ( es_config is defined and es_config.changed) or ( keystore_create is defined and keystore_create.changed) or (kernel_params is defined and kernel_params.changed) or (kestore_write is defined and keystore_write.changed) }}"
    name: "smd_infra_elastic"
    user: root
    image: "{{ elasticsearch_docker_image }}:{{ elasticsearch_docker_tag }}"
    detach: true
    cpu_period: "{{ elasticsearch_docker_container_cpu_period }}"
    cpu_quota: "{{ ( elasticsearch_docker_container_cpu_period * elasticsearch_docker_container_cpu_count ) | int }}"
    #cpu_quota: "{{ ( elasticsearch_docker_container_cpu_period * elasticsearch_docker_container_cpu_count ) | int }}"
    #cpu_quota: "{{ ( ( elasticsearch_docker_container_cpu_period / ansible_processor_vcpus ) * elasticsearch_docker_container_cpu_count ) | int }}"
    memory: "{{ elasticsearch_docker_container_memory | default( ( ansible_memtotal_mb / 2 ) | int ) }}m"
    ulimits: 
      - memlock:-1:-1
    env:
      node.name: "{{ ansible_hostname }}"
      ES_JAVA_OPTS: "-Xms{{ ( elasticsearch_docker_container_memory | default( ( ansible_memtotal_mb / 2 ) | int ) / 2) | int }}m -Xmx{{ (elasticsearch_docker_container_memory | default( ( ansible_memtotal_mb / 2 ) | int ) / 2) | int }}m" 
    restart_policy: unless-stopped
    log_driver: json-file
    log_options:
      max-size: '30m'
      max-file: '3'
    labels:
      SERVICE_TYPE: elasticsearch 
      SERVICE_OWNER: infra
      SERVICE_LABEL: "{{ elasticsearch_cluster_name }}"
    published_ports:
      - "{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}:9200"
      - "{{ elasticsearch_network_address }}:9300:9300"
    volumes:
      - "{{ elasticsearch_data_dir }}:/usr/share/elasticsearch/data/:rw,Z"
      - "{{ elasticsearch_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z"
      - "{{ elasticsearch_config_dir }}/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore:ro,Z"
      - "{{ elasticsearch_certificate_dir }}:/usr/share/elasticsearch/config/certs/:ro,Z"
      - "{{ elasticsearch_config_dir }}/role_mapping.yml:/usr/share/elasticsearch/config/role_mapping.yml:ro,Z"
      - "{{ elasticsearch_snapshot_dir_host }}:{{ elasticsearch_snapshot_dir_dest }}:rw"
  register: container_deploy
  tags:
    - deploy

- name: Wait for elasticsearch port to be opened
  wait_for:
    state: started
    host: "{{ elasticsearch_network_address }}"
    port: "{{ elasticsearch_network_port }}"
    delay: 1
    timeout: 120
  tags:
    - deploy

- name: Check elasticsearch cluster status
  uri: 
    method: GET
    url_username: elastic
    url_password: "{{ secrets.elasticsearch.bootstrap.password }}"
    url: "{% if elasticsearch_security_http_enabled %}https{% else %}http{% endif %}://{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}/_cluster/health"
    remote_src: True
    return_content: True
    validate_certs: False
    body_format: json
  register: cluster_check
  until: cluster_check.status in [ 200 ] and cluster_check.json.status == "green"
  delay: 15 
  retries: 5
  when: elasticsearch_cluster_check
  tags:
    - deploy

- name: Check if pass changed status file exists
  stat: 
    path: "{{ elasticsearch_config_dir }}/pass_changed"
  run_once: True
  register: pass_status_file
  tags:
    - configuration
    - users
    - password

- name: Change users password
  uri: 
    method: POST
    url_username: elastic
    url_password: "{{ secrets.elasticsearch.bootstrap.password }}"
    url: "{% if elasticsearch_security_http_enabled %}https{% else %}http{% endif %}://{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}/_security/user/{{ item.key }}/_password"
    remote_src: True
    return_content: True
    validate_certs: False
    body_format: json
    body: "{ 'password' : '{{ item.value }}' }"
  run_once: True
  with_dict: "{{ secrets.elasticsearch.users }}"
  when: elasticsearch_users_internal_pass_change and pass_status_file.stat.exists == False
  register: user_pass_change
  until: user_pass_change.status in [ 200, 204 ]
  delay: 3 
  retries: 5
  tags:
    - configuration
    - users
    - password

- name: Create pass changed status file
  file:
    state: touch
    path: "{{ elasticsearch_config_dir }}/pass_changed"
  run_once: True
  when: pass_status_file.stat.exists == False and user_pass_change.results|selectattr('status','equalto',200)|list|length == secrets.elasticsearch.users|length
  tags:
    - configuration
    - users
    - password

- include_tasks: elastic_users.yml
  vars:
    users_definition_file: "{{ elasticsearch_users_file | default(role_path + '/files/users/definition.yml') }}"
    roles_definition_file: "{{ elasticsearch_roles_file | default(role_path + '/files/roles/definition.yml') }}"
  when: elasticsearch_users_create
  tags:
    - configuration
    - users

- name: Check if license status file exists
  stat: 
    path: "{{ elasticsearch_config_dir }}/license_applied"
  run_once: True
  register: license_status_file
  tags:
    - configuration
    - license

- name: Enable elasticsearch monitoring collection
  uri:
    method: PUT
    url_username: elastic
    url_password: "{{ secrets.elasticsearch.users.elastic }}"
    url: "{% if elasticsearch_security_http_enabled %}https{% else %}http{% endif %}://{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}/_cluster/settings"
    remote_src: True
    return_content: True
    validate_certs: False
    body_format: json
    body: |
      {
       "persistent": {
         "xpack.monitoring.collection.enabled": true
       }
      }
  run_once: True
  when: elasticsearch_metricbeat_monitoring_enabled
  register: enable_monitoring_collection 
  until: enable_monitoring_collection.status in [ 200, 204 ]
  delay: 3 
  retries: 5
  tags:
    - configuration
    - monitoring 

- name: Disable elasticsearch default monitoring collection
  uri:
    method: PUT
    url_username: elastic
    url_password: "{{ secrets.elasticsearch.users.elastic }}"
    url: "{% if elasticsearch_security_http_enabled %}https{% else %}http{% endif %}://{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}/_cluster/settings"
    remote_src: True
    return_content: True
    validate_certs: False
    body_format: json
    body: |
      {
       "persistent": {
         "xpack.monitoring.elasticsearch.collection.enabled": false 
       }
      }
  run_once: True
  when: elasticsearch_metricbeat_monitoring_enabled
  register: disable_default_monitoring_collection 
  until: disable_default_monitoring_collection.status in [ 200, 204 ]
  delay: 3 
  retries: 5
  tags:
    - configuration
    - monitoring 

- name: Apply license
  uri:
    method: POST
    url_username: elastic
    url_password: "{{ secrets.elasticsearch.users.elastic }}"
    url: "{% if elasticsearch_security_http_enabled %}https{% else %}http{% endif %}://{{ elasticsearch_network_address }}:{{ elasticsearch_network_port }}/_license"
    remote_src: True
    return_content: True
    validate_certs: False
    body_format: json
    body: "{{ lookup('file', lookup('env','PWD') + '/files/elasticsearch/license/license.json') }}"
  run_once: True
  when: elasticsearch_license_enabled and license_status_file.stat.exists == False
  register: license_apply
  until: license_apply.status in [ 200, 204 ]
  delay: 3 
  retries: 5
  tags:
    - configuration
    - license

- name: Create license status file
  file:
    state: touch
    path: "{{ elasticsearch_config_dir }}/license_applied"
  run_once: True
  when: license_status_file.stat.exists == False and license_apply.status is defined and license_apply.status == 200 and license_apply.json.license_status == 'valid'
  tags:
    - configuration
    - license
