---

roles:

  - fluentd_role:
      cluster:
        - monitor
        - manage_index_templates
      indices:
        - names:
            - 'logstash*'
          privileges:
            - all
          field_security:
            grant:
              - '*'
      metadata:
        version: 1

  - logstash_writter:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names:
            - 'logstash*'
          privileges:
            - manage
            - manage_ilm
            - read
            - write
            - delete
            - create_index
      metadata:
        version: 1

  - filebeat_writter:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names:
            - 'filebeat*'
          privileges:
            - manage
            - read
            - write
            - create_index
      metadata:
        version: 1

  - metricbeat_writter:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names:
            - 'metricbeat*'
          privileges:
            - manage
            - read
            - write
            - create_index
      metadata:
        version: 1

  - heartbeat_writter:
      cluster:
        - monitor
        - manage_index_templates
        - manage_ilm
      indices:
        - names:
            - 'heartbeat*'
          privileges:
            - manage
            - read
            - write
            - create_index
      metadata:
        version: 1

  - api_monitoring:
      cluster:
        - monitor
      metadata:
        version: 1
