---

- name: Install required packages
  gather_facts: False
  hosts: elk
  become: True

  tasks:

    - name: Install SO packages
      yum:
        state: latest
        update_cache: True
        name:
          - python3
          - python3-pip
      vars:
        ansible_python_interpreter: /usr/bin/python2

    - name: Install python packages
      pip:
        executable: pip3
        name:
          - docker
