---

- name: Install required packages
  gather_facts: False
  hosts: elk
  become: True

  tasks:

    - name: Set max file descriptors
      pam_limits:
        domain: '*'
        limit_type: "-"
        limit_item: nofile
        value: 65535

    - name: Install SO packages
      yum:
        state: latest
        update_cache: True
        name:
          - python3
          - python3-pip

    - name: Install python packages
      pip:
        executable: pip3
        name:
          - docker
